# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    continue-on-error: true
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'


      - name: Flutter action
      # You may pin to the exact commit or the version.
      # uses: subosito/flutter-action@26bf50084a0c218b5b715a3641c36eac84fd2136
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: 1.22.6
          channel: stable
      - run: flutter pub get
      - run: flutter build apk
